### ISSUE TITLE
BUG: super_clipboard Cause PlatformException(channel-error, Unable to establish connection on channel., null, null) on Android devices

### ISSUE THREAD

**Issue by EMUNES** [superlistapp/super_native_extensions#353]
I found this exception always occur on Android devices, if I use `super_clipboard` (or packages depending on `super_clipboard`, like `flutter_quill`) with `shared_preferences` package. I can use `shared_preference` with other dozens of packages, but once with `super_clipboard`, the exception occurs which I can not get rid of. I report this BUG here because this is the only platform-related package I can find to cause this problem.

This exception will cause Android app unable to open. The app will hang.

This exception won't occur on Windows11 build. It won't occur if `super_clipboard` is the only package dependency. 

ENV: flutter version: 3.19.6 and dart 3.3.4, Windows 11
VERSION: `supper_clipboard` 0.7.3 up to 0.8.12

Minimal code for reproduce:

*pubspec.yml*:

```yaml
name: fix
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3 # Persistent settings.
  # flutter_quill: "9.0.0"
  super_clipboard: "0.7.3" # up to "8.0.12"
  # flutter_keyboard_visibility: ^6.0.0 # no problem.
  # url_launcher: ^6.2.6 # no problem.
  # device_info_plus: ^10.1.0 # no problem.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

Main code to run:

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final prefs = await SharedPreferences.getInstance(); // Exception here.

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```
