### ISSUE TITLE
device_info_plus 11.x.y

### ISSUE THREAD

**Issue by lukepighetti** [superlistapp/super_native_extensions#494]
there's a new major release for device_info_plus and even though super_native_extensions appears to handle 10.x.y – 11.x.y we keep getting this error when doing pub get

```
Resolving dependencies...
Because no versions of super_clipboard match >0.8.24 <0.9.0 and super_clipboard 0.8.24 depends on super_native_extensions ^0.8.24, super_clipboard ^0.8.24 requires super_native_extensions ^0.8.24.
Because super_native_extensions 0.8.24 depends on device_info_plus ^10.0.1 and no versions of super_native_extensions match >0.8.24 <0.9.0, super_native_extensions ^0.8.24 requires device_info_plus ^10.0.1.
Thus, super_clipboard ^0.8.24 requires device_info_plus ^10.0.1.
So, because sep_app depends on both device_info_plus ^11.2.2 and super_clipboard ^0.8.24, version solving failed.
```

**Comment by shiena** [comment]
Dependency conflicts could be avoided by setting dependency_overrides in pubspec.yaml.

```yaml
dependencies:
    super_drag_and_drop: '>=0.8.0'

depenency_overrides:
    device_info_plug: '>=11.0.0 <12.0.0'
```
