### ISSUE TITLE
[Windows] No drag image within the application

### ISSUE THREAD

**Issue by leonx98** [superlistapp/super_native_extensions#52]
Hey Matej,

the `super_drag_and_drop` works fine on macOS. However, it causes a few problems on Windows. When start dragging, we don't have a drag image inside the application. If we drag the across the application boundary, we see the drag image.

We have a list of files and each row has a `DragItemWidget`.   
As soon as we start dragging we get the following exception:

<details>
<summary>Exception</summary>

```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 3453 pos 12: '!debugNeedsPaint': is not true.
package:flutter/…/rendering/proxy_box.dart:3453
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      RenderRepaintBoundary.toImage
package:flutter/…/rendering/proxy_box.dart:3453
#3      DragItemWidgetState._getSnapshot
package:super_drag_and_drop/src/draggable_widget.dart:88
#4      DraggableFileState._draggableWrapper.<anonymous closure>
package:spaces_client/…/list/draggableFile.dart:151
#5      DragItemWidgetState.createItem
package:super_drag_and_drop/src/draggable_widget.dart:98
#6      DraggableWidget.dragConfigurationForItems
package:super_drag_and_drop/src/draggable_widget.dart:184
<asynchronous suspension>
#7      _DragDetector._maybeStartDragWithSession
package:super_drag_and_drop/src/drag_internal.dart:161
<asynchronous suspension
```

</details>

According to this issue https://github.com/flutter/flutter/issues/22308, I tried a 20ms delay before i request the snapshot image. The exception is then gone, but we still don't have a drag image within the application (see video below).

Maybe it is also important to mention that we get the following error message as soon as we start the application:

<details>
<summary>Error</summary>

```dart
ERROR [] Unexpected error The window has already been registered as a drop target. (0x80040101) at src\.\win32\drop.rs:138:43
```

</details>

<details>
<summary>Implementation</summary>

```dart
return DragItemWidget(
        key: dragItemKey,
        dragItemProvider: (snapshot, session) async {
          final fileName = widget.fileItem.name;

          List<Map<String, dynamic>> encodedFileItems = [];
          if (viewModel.isInSelectionMode) {
            final selectedFileItems = viewModel.getSelectedFiles();
            selectedFileItems.forEach((f) {
              encodedFileItems.add(f.toJson());
            });
          } else {
            encodedFileItems.add(widget.fileItem.toJson());
          }

          await Future.delayed(const Duration(milliseconds: 20));
          final img = await snapshot();

          final item = DragItem(
            image: img,
            suggestedName: fileName,
            localData: encodedFileItems,
          );

          if (!item.virtualFileSupported) {
            return item;
          }

          if (!widget.fileItem.isDirectory) {
            item.addVirtualFile(
              format: Formats.fileUri,
              provider: (sinkProvider, progress) async {
                final fileSize = widget.fileItem.size;
                final sink = sinkProvider(fileSize: fileSize);

                await viewModel.streamFile(
                  file: widget.fileItem,
                  onReceiveData: (data) {
                    sink.add(data);
                  },
                  onStreamDone: () {
                    sink.close();
                  },
                );
              },
            );
          }

          return item;
        },
        allowedOperations: () => [DropOperation.copy],
        child: DraggableWidget(
          dragItemsProvider: (context) {
            if (viewModel.isInSelectionMode) {
              viewModel.dragItemKeys.removeWhere((e) => e.currentState == null);
              return viewModel.dragItemKeys.map((e) => e.currentState!).toList();
            } else {
              return [dragItemKey.currentState!];
            }
          },
          child: child,
        ),
      );
    }
```

</details>

https://user-images.githubusercontent.com/25419507/214842890-85c69e9a-c1c0-4662-8ca2-ff73744a0011.mov

**Comment by knopp** [comment]
Does this problem persist after you add a DropRegion somewhere in your page?

The way drag avatars work on windows is a bit weird. The window needs to be registered for dropping and then from drop callback call API on a helper COM object to draw the avatar.

This currently only happens if there is a drop region within the app, even if inactive.

Also note that there is a pretty big PR coming in https://github.com/superlistapp/super_native_extensions/pull/47, which also fixes some windows bugs, but I'm not sure it is related.

**Comment by leonx98** [comment]
Yes, each row is also a DropRegion. The folder for example to move files in there. However, this does not react at all when hovering over.
Currently we don't use any other drag and drop plugin.

**Comment by knopp** [comment]
If you run the executable through `cmd`, is there any error message printed on startup?

**Comment by knopp** [comment]
Can you try 0.2.0 and let me know if it behaves same?

**Comment by leonx98** [comment]
> If you run the executable through `cmd`, is there any error message printed on startup?

There are still the same error messages.

> Can you try 0.2.0 and let me know if it behaves same?

Unfortunately it still does not work. Still the same errors...

**Comment by knopp** [comment]
Oh, I missed the error message. It says that window has already been registered as drop target. There can be only one drop target per HWND. Are you really sure there is no other drop plugin active? That would explain the situation entirely.

**Comment by knopp** [comment]
If you can post here your pubspec.yam I can take a look.

**Comment by leonx98** [comment]
Sure :)

```yaml
name: *removed
description: A tool to store and exchange files with your team.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.30.0+snapshot

environment:
  sdk: ">=2.17.0 <3.0.0"

# How to use local sources for a plugin:
# plugin:
#   path: ../path_to/plugin
dependencies:
  addressbook:
    git:
      url: https://github.com/skalio/flutter-addressbook.git
      ref: ae2e654
  animated_check: ^1.0.5
  animated_cross: ^1.0.0
  animated_text_kit: ^4.2.1
  animations: ^2.0.3
  blurhash_dart: ^1.0.2
  camera: ^0.9.4+18
  chewie: ^1.3.0
  collection: ^1.15.0
  confetti: ^0.7.0
  connectivity_plus: ^2.2.0
  copy_with_extension: ^4.0.2
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  email_validator: ^2.0.1
  encrypt: ^5.0.1
  equatable: ^2.0.3
  file_picker: ^5.2.2
  file_selector: ^0.8.3
  file_selector_macos: ^0.8.2+1
  flextras: ^0.0.2
  flutter:
    sdk: flutter
  flutter_appauth: ^4.2.1
  flutter_cache_manager: ^3.3.0
  flutter_chips_selector:
    git:
      url: https://github.com/skalio/flutter-chips-selector.git
      ref: 4bf54a9
  flutter_custom_tabs: ^1.0.4
  flutter_font_awesome_pro:
    git:
      url: git@gitlab.skalio.net:tools/flutter-font-awesome-pro.git
      ref: 14feac60
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  gettext: ^1.2.0
  gettext_parser: ^0.2.0
  google_fonts: ^2.3.1
  in_app_review: ^2.0.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  jwt_decoder: ^2.0.1
  loading_indicator: ^3.0.2
  lottie: ^2.0.0
  mime_type: ^1.0.0
  native_file_explorer_launcher:
    git:
      url: https://github.com/skalio/native-file-explorer-launcher
      ref: 8f42f4b
  open_filex: ^4.3.1
  path: ^1.8.0
  path_drawing: ^1.0.0
  path_provider: ^2.0.11
  platform: ^3.1.0
  provider: ^6.0.0
  queue: ^3.1.0+1
  share_plus: ^6.3.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.2.0
  sliver_tools: ^0.2.5
  super_drag_and_drop: ^0.2.0
  synchronized: ^3.0.0
  tuple: ^2.0.0
  uni_links: ^0.5.1
  uni_links_desktop: ^0.1.4
  url_launcher: ^6.0.13
  usage:
    # TODO reference back to upstream after https://github.com/dart-lang/usage/pull/166 lands
    git:
      url: https://github.com/skalio/usage.git
      ref: 840f8fa
  uuid: ^3.0.5
  video_player: ^2.2.6
  watcher: ^1.0.1
  web_socket_channel: ^2.1.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e
  flutter_commons:
    git:
      url: git@gitlab.skalio.net:commons/flutter-commons.git
      ref: 0d15ad642be78afa9a5296e71f29dda5aedc9b3b

dev_dependencies:
  build_runner: ^2.1.11
  copy_with_extension_gen: ^4.0.2
  dart_code_metrics: ^4.15.2
  dependency_validator: ^3.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  mocktail: ^0.3.0
  msix: ^3.7.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - pubspec.yaml
    - assets/avatars/
    - assets/colors/
    - assets/fonts/
    - assets/lottieAnimations/
    - assets/logos/
    - assets/images/
    - assets/customIcons/
    - assets/customIcons/fileTypes/
    - assets/timezoneIds.json
    - l10n/l10ns/de_DE.mo
```

**Comment by knopp** [comment]
Thanks. I tried a basic drag & drop app on windows with these packages (except of the private ones) but I couldn't reproduce the problem. Just in case, could you post the content of `generated_plugin_registrant.cc` file inside the `window/flutter` directory, to make sure I'm not missing something?

I don't suppose you call `RegisterDragDrop` on flutter HWND manually anywhere in the windows code?

**Comment by knopp** [comment]
We could potentially call `RevokeDragDrop` before trying to register, which should override whatever else is there registered for drag, but it would be good to figure out what exactly is causing this.

**Comment by leonx98** [comment]
> I don't suppose you call `RegisterDragDrop` on flutter HWND manually anywhere in the windows code?

No, we don't.

Here's our `generated_plugin_registrant.cc`:    
```cpp
//
//  Generated file. Do not edit.
//

// clang-format off

#include "generated_plugin_registrant.h"

#include <connectivity_plus_windows/connectivity_plus_windows_plugin.h>
#include <file_selector_windows/file_selector_windows.h>
#include <irondash_engine_context/irondash_engine_context_plugin_c_api.h>
#include <native_file_explorer_launcher/native_file_explorer_launcher_plugin.h>
#include <share_plus/share_plus_windows_plugin_c_api.h>
#include <super_native_extensions/super_native_extensions_plugin_c_api.h>
#include <uni_links_desktop/uni_links_desktop_plugin.h>
#include <url_launcher_windows/url_launcher_windows.h>
#include <window_size/window_size_plugin.h>

void RegisterPlugins(flutter::PluginRegistry* registry) {
  ConnectivityPlusWindowsPluginRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("ConnectivityPlusWindowsPlugin"));
  FileSelectorWindowsRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("FileSelectorWindows"));
  IrondashEngineContextPluginCApiRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("IrondashEngineContextPluginCApi"));
  NativeFileExplorerLauncherPluginRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("NativeFileExplorerLauncherPlugin"));
  SharePlusWindowsPluginCApiRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("SharePlusWindowsPluginCApi"));
  SuperNativeExtensionsPluginCApiRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("SuperNativeExtensionsPluginCApi"));
  UniLinksDesktopPluginRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("UniLinksDesktopPlugin"));
  UrlLauncherWindowsRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("UrlLauncherWindows"));
  WindowSizePluginRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("WindowSizePlugin"));
}
```

Strange... I even commented out all the `DropRegions` and I still get the error message that the window has already been registered as a drop target 🤔😅

**Comment by knopp** [comment]
> Strange... I even commented out all the DropRegions and I still get the error message that the window has already been registered as a drop target 🤔😅

That is to be expected. The drop target is registered also when there is anything draggable (as the drop target is responsible for showing drag indicators in the window).

This is quite baffling I have to admit. I will make special branch that will try to unregister the drop handler first as well as add extra logging.

**Comment by knopp** [comment]
Could you try this revision:  https://github.com/superlistapp/super_native_extensions/commit/07a00bedba64313f06c2d0100175534600249473 and let me know if it behaves differently?

**Comment by leonx98** [comment]
Stil the same error...

**Comment by knopp** [comment]
Would this not work?
```yaml
super_drag_and_drop:
    git:
      url: https://github.com/superlistapp/super_native_extensions.git
      ref: 07a00bedba64313f06c2d0100175534600249473
      path: super_drag_and_drop
```

**Comment by leonx98** [comment]
> Would this not work?
> 
> ```yaml
> super_drag_and_drop:
>     git:
>       url: https://github.com/superlistapp/super_native_extensions.git
>       ref: 07a00bedba64313f06c2d0100175534600249473
>       path: super_drag_and_drop
> ```

Oh okay, yeah it works too. But there are no additional logs as well.

**Comment by knopp** [comment]
No log even after `flutter clean`? The logger obviously works (because of the error message), and it is initialized with info level, so it should print the info message.

If you run `dir` inside `windows\flutter\ephemeral\.flutter_symlinks` does the `super_native_extensions` plugin point to correct directory (should have the commit hash in it)

**Comment by leonx98** [comment]
No, it points to: `[C:\\Users\\leon\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\super_native_extensions-0.2.0\\]`.   
Even though there is a `super_native_extensions-07a00bedba64313f06c2d0100175534600249473` directory in `C:\Users\leon\AppData\Local\Pub\Cache\git\`.  
 
I already tried `flutter pub cache clean`, `flutter clean` and the deleted the `pubspec.lock`. Do you have any other ideas? 🤔

**Comment by knopp** [comment]
What does pubspec.lock say about `super_native_extensions`? I think maybe you might need add dependency override for super_native_extension

```yaml
dependency_overrides:
  super_native_extensions:
    git:
      url: https://github.com/superlistapp/super_native_extensions.git
      ref: 07a00bedba64313f06c2d0100175534600249473
      path: super_native_extensions
```

I didn't realise it is an inner dependency and will probably need to be specified separately.
