### ISSUE TITLE
[Android] Failed to apply plugin class 'CargoKitPlugin'

### ISSUE THREAD

**Issue by leonx98** [superlistapp/super_native_extensions#75]
Hey Matej,

we actually don't using the plugin (super_drag_and_drop) on Android (only on macOS and Windows), but when we trying to build our Android version, there appear the following error message:

```console
FAILURE: Build failed with an exception.

* Where:
Script '/Users/leon/.pub-cache/hosted/pub.dev/super_native_extensions-0.2.2/cargokit/gradle/plugin.gradle' line: 90

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin class 'CargoKitPlugin'.
   > No such property: childProjects for class: java.util.TreeMap$Entry

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1
Exited
```

**Comment by knopp** [comment]
Thank you for the report. Looks like a bug in CargoKit. Since I can't reproduce this locally, could you add dependency override for `super_native_extension` like this:

```yaml
dependency_overrides:
  super_native_extensions:
    git:
      url: https://github.com/superlistapp/super_native_extensions.git
      ref: ded6203800a0f82dfaf0a53030ab32884b11d249
      path: super_native_extensions
```

And let me know if it builds?
